### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by clovisdasilvaneto** [comment]
LGTM!

**Comment by diegonvs** [comment]
LGTM

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
ci:retest

**Comment by clovisdasilvaneto** [comment]
Pull request forwarded to https://github.com/pedroqueiroz94/liferay-portal/pull/undefined. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by clovisdasilvaneto** [comment]
Pull request forwarded to https://github.com/pedroqueiroz/liferay-portal/pull/97. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
