### PR TITLE
LPS-77345 Path fixing

### PR DESCRIPTION
**Pull request by rigosouza**

### CODE REVIEW

**Comment by rigosouza** [comment]
Hi @alinedoleron, seems Grid's Help Text mark up is not updated, may you fix it? All other fields are ok, only happens on Grid.

**Comment by rigosouza** [comment]
ci:test

**Comment by alinedoleron** [comment]
Hi @rigosouza, I'll take a look and send another PR that include Grid's markup update.

**Comment by rigosouza** [comment]
ci:test

**Comment by rafaprax** [comment]
Hey @vicnate5, Could you please check if these errors are related with these changes? I think they aren't related but if you can confirm will be nice.
Thx

**Comment by vicnate5** [comment]
@rafaprax `Forms#SelectAndRemoveMultipleOptionsInSelectFromListField` failure looks related to this change. I can take a look at this.

**Comment by vicnate5** [comment]
Forwarded https://github.com/rafaprax/liferay-portal/pull/382

**Comment by vicnate5** [comment]
ci:close

**Comment by vicnate5** [comment]
ci:close

**Comment by pedroqueiroz** [comment]
ci:close

**Pull request closed without merging**
