### PR TITLE
[TECHNICAL SUPPORT] LPS-77158 Quickly switching language in web content breaks the content of editor

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hello,

The fix is to wait for the editor at initial render with setHTML, and to compare the value with the current locale's value.
Please review the PR.

@jbalsas

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @NemethNorbert, could you add a commit on top using the new `componentReady` promise-based API so we merge the final code into `master`?

For backport purposes, only the first one should be used.

**Comment by NemethNorbert** [comment]
Hey @jbalsas , I thought `componentReady` is only available in master. This is aimed to be a unique fix to 7.0.x. As in master this issue is not reproducible due how the UI is disabled while the form is loading.

**Comment by jbalsas** [comment]
Hey @NemethNorbert, if this is not reproducible in `master`, shouldn't it go straight to `7.0.x` then?

**Comment by NemethNorbert** [comment]
Hey @jbalsas , Sorry I am confused now. It`s a 7.0.x PR, or In case it is a special fix I should go straight to ER?

**Comment by jbalsas** [comment]
If it is a unique fix for 7.0, then this should be done over a `7.0.x` branch and sent against `liferay-portal-ee@7.0.x` to the `liferay` user after the reviews.

Seeing the code, though, this adds a new API that we need to make sure stays in `master`, so this should be split into the `editor` bits to master, and the `ddm` part just to `7.0.x`.

**Comment by NemethNorbert** [comment]
Hey @jbalsas,
I can send a PR against `liferay-portal-ee@7.0.x` to the `liferay` user, if you are okey with that.
About your second statement could you answer a few questions?
-Why does this commit add a new API?
-Why should we merge it into master as well, if it`s not reproducible there?
-If we should merge it to master, why just the editor part?

Thank you.

**Comment by jbalsas** [comment]
Hey @NemethNorbert,

> - Why does this commit add a new API?

By calling `Liferay.component(id, component)` you are triggering the `component:registered` event. That is a new API that you are using to fix the issue

> - Why should we merge it into master as well, if it`s not reproducible there?

Because new APIs always need to remain in newer versions. If we don't, someone using this will see it's code break by an API removal when they upgrade to newer versions. Committing a new API on older versions is an automatic breaking change for the new one if it's not added yet.

> - If we should merge it to master, why just the editor part?

The editor part adds the new API and needs to remain for future versions. If the ddm part is useless, then there's no need to add it.

> I can send a PR against liferay-portal-ee@7.0.x to the liferay user, if you are okey with that.
About your second statement could you answer a few questions?

I think, based on this, we should send the editor portion fix to `master` fix and then do the backport completing it with the ddm code.

**Comment by NemethNorbert** [comment]
Hey @jbalsas ,
Thank you for the clarification. I start working on it and I send a PR to you.

@clovisdasilvaneto ,
Please close this PR

**Pull request closed without merging**
