### PR TITLE
LPS-77345 Add check boolean condition in _isValueEmpty method, to copy boolean values in the new field

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by clovisdasilvaneto** [comment]
ci:test

**Comment by rigosouza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rigosouza** [comment]
Resent at: https://github.com/clovisdasilvaneto/liferay-portal/pull/28

**Comment by rigosouza** [comment]
ci:close

**Comment by rigosouza** [comment]
ci:close

**Pull request closed without merging**
