### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
LGTM!

**Comment by clovisdasilvaneto** [comment]
ci:retest

**Comment by clovisdasilvaneto** [comment]
- https://testray.liferay.com/reports/production/logs/test-1-4/1522246740100/test-portal-acceptance-pullrequest(master)/2950/functional-tomcat80-mysql56-jdk8/8/0/LocalFile.Forms_EditAllFormFieldsTypesUsedBySystemSettings/summary.html.gz
- https://testray.liferay.com/reports/production/logs/test-1-4/1522246740100/test-portal-acceptance-pullrequest(master)/2950/functional-tomcat80-mysql56-jdk8/1/2/LocalFile.Forms_ViewDefaultFieldNamesWithPunctuationCharacters/summary.html.gz

@pedroqueiroz and @rafaprax would you guys mind taking a look in these tests wich are failing?

**Comment by pedroqueiroz** [comment]
@clovisdasilvaneto , this is not related. :)

**Comment by clovisdasilvaneto** [comment]
Sounds good, I'll foward this PR to you @pedroqueiroz

**Comment by clovisdasilvaneto** [comment]
Pull request forwarded to https://github.com/rafaprax/liferay-portal/pull/452. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
