### PR TITLE
LPS-77057 Buttons in Modal isn't in new lexicon version

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test

**Comment by diegonvs** [comment]
ci:stop

**Comment by diegonvs** [comment]
ci:test

**Comment by clovisdasilvaneto** [comment]
LGTM.

**Comment by alinedoleron** [comment]
LGTM

**Comment by clovisdasilvaneto** [comment]
Pull request forwarded to https://github.com/pedroqueiroz/liferay-portal/pull/107. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by vicnate5** [comment]
@pedroqueiroz tests are OK, only ran the acceptance forms tests, not all of them.

**Pull request closed without merging**
