### PR TITLE
LPS-77549 Remove line of Rules action and adjust background color

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
ci:retest

**Comment by brunobasto** [comment]
@interaminense, can you review please?

**Comment by clovisdasilvaneto** [comment]
LGTM!

**Comment by clovisdasilvaneto** [comment]
Pull request forwarded to https://github.com/rafaprax/liferay-portal/pull/301. [See changes here.](https://github.com/clovisdasilvaneto/liferay-portal/compare/31a3afe62d90~1...31a3afe62d90) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by clovisdasilvaneto** [comment]
Pull request forwarded to https://github.com/rafaprax/liferay-portal/pull/444. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
