### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
LGTM!

**Comment by clovisdasilvaneto** [comment]
ci:test

**Comment by clovisdasilvaneto** [comment]
- https://testray.liferay.com/reports/production/logs/test-1-21/1522246658196/test-portal-acceptance-pullrequest(master)/1740/functional-tomcat80-mysql56-jdk8/1/1/LocalFile.Forms_SearchFormRecordMultipleEntries/summary.html.gz
- https://testray.liferay.com/reports/production/logs/test-1-21/1522246658196/test-portal-acceptance-pullrequest(master)/1740/functional-tomcat80-mysql56-jdk8/2/0/LocalFile.Forms_AddElementSetsWithTranslation/summary.html.gz
- https://testray.liferay.com/reports/production/logs/test-1-21/1522246658196/test-portal-acceptance-pullrequest(master)/1740/functional-tomcat80-mysql56-jdk8/8/0/LocalFile.Forms_EditAllFormFieldsTypesUsedBySystemSettings/summary.html.gz

@pedroqueiroz and @rafaprax would you guys mind taking a look in these tests wich are failing?

**Comment by pedroqueiroz** [comment]
@clovisdasilvaneto , these failures are not related! :)

**Comment by clovisdasilvaneto** [comment]
Pull request forwarded to https://github.com/rafaprax/liferay-portal/pull/453. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
