### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
@clovisdasilvaneto, I think these failures are not related to my fix.

**Comment by clovisdasilvaneto** [comment]
Good @alinedoleron LGTM!

**Comment by alinedoleron** [comment]
resent to https://github.com/rafaprax/liferay-portal/pull/473

**Pull request closed without merging**
