### PR TITLE
LPS-79088 Fix margin top according to view port

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by alinedoleron** [comment]
LGTM!

**Comment by clovisdasilvaneto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by clovisdasilvaneto** [comment]
LGTM!

**Comment by clovisdasilvaneto** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/451. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
