### PR TITLE
LPS-76453 Apply Clay classes in text field tooltip

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by clovisdasilvaneto** [comment]
LGTM!

**Comment by interaminense** [comment]
LGTM!

**Comment by clovisdasilvaneto** [comment]
ci:test

**Comment by alinedoleron** [comment]
ci:retest

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
ci:test

**Comment by clovisdasilvaneto** [comment]
Pull request forwarded to https://github.com/pedroqueiroz94/liferay-portal/pull/89. [See changes here.](https://github.com/clovisdasilvaneto/liferay-portal/compare/19ac993e900b~7...19ac993e900b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
