### PR TITLE
LPS-77800 Apply Clay css classes

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
ci:retest

**Comment by alinedoleron** [comment]
ci:test

**Comment by clovisdasilvaneto** [comment]
LGTM

**Comment by clovisdasilvaneto** [comment]
Pull request forwarded to https://github.com/pedroqueiroz94/liferay-portal/pull/79. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
