### PR TITLE
LPS-84335 Fix return statement

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by clovisdasilvaneto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by clovisdasilvaneto** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-portal/pull/919. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
