### PR TITLE
LPS-77046 Typography and color of Help Text are different in some fields.

### PR DESCRIPTION
**Pull request by diegonvs**
From: https://issues.liferay.com/browse/LPS-77046

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test

**Comment by alinedoleron** [comment]
LGTM!

**Comment by alinedoleron** [comment]
ci:test

**Comment by clovisdasilvaneto** [comment]
Pull request forwarded to https://github.com/pedroqueiroz/liferay-portal/pull/126. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
