### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests tomcat 9

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
Hi @vicnate5 and @rigosouza. I took a look on this poshi error (LocalFile.Forms#ViewFieldValidationIsNotBypassedWhenNextButtonIsHitTwice) and I think it should searching for:

`//ul[contains(@class,'multi-step-nav')]//li[not(contains(@class,'active'))]/div[contains(.,'Page 1')] | //ul[contains(@class,'multi-step-nav')]//li[not(contains(@class,'complete'))]/div[contains(.,'Page 1')] | //ul[contains(@class,'multi-step-progress-bar')]/li[not(contains(@class,'active'))]//div[contains(.,'Page 1') and contains(@class,'multi-step-indicator-label')] `

instead of `ol` tag.
Please, could you guys take a look on this?

**Comment by clovisdasilvaneto** [comment]
LGTM!

**Comment by rigosouza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rigosouza** [comment]
Resent here: https://github.com/pedroqueiroz/liferay-portal/pull/139

**Comment by rigosouza** [comment]
ci:close

**Pull request closed without merging**
