### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
ci:restest

**Comment by alinedoleron** [comment]
ci:stop

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
ci:reopen

**Comment by rafaprax** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
Test failures are not related. Is this PR "LGTM", @clovisdasilvaneto ? :D

**Comment by clovisdasilvaneto** [comment]
Yes @pedroqueiroz .

**Comment by clovisdasilvaneto** [comment]
Pull request forwarded to https://github.com/pedroqueiroz/liferay-portal/pull/102. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
